name: Test GT3X converter
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Run converter
        env:
          DATA_DIR: ${{ github.workspace }}/data
        run: |
          Rscript pipeline/convert_gt3x_to_csv.R
          ls -lh data || true
