name: GT3X → CSV Converter

on:
  push:
    paths:
      - '**/convert_gt3x_to_csv.R'
      - 'pipeline/**'
      - 'scripts/**'
      - 'data/**'
      - '.github/workflows/gt3x-convert.yml'
  pull_request:
    paths:
      - '**/convert_gt3x_to_csv.R'
      - 'pipeline/**'
      - 'scripts/**'
      - 'data/**'
      - '.github/workflows/gt3x-convert.yml'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # gives remotes/devtools a token if anything still installs from GitHub
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true   # fast binaries on Ubuntu

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends unzip

      # Pre-install CRAN deps so your script doesn't try GitHub
      - name: Install R packages (CRAN)
        run: |
          Rscript -e 'repos <- c(CRAN="https://cloud.r-project.org"); install.packages(c("read.gt3x"), repos = repos, Ncpus = parallel::detectCores())'

      - name: Locate converter script
        id: find_script
        shell: bash
        run: |
          set -euo pipefail
          script_path="$(git ls-files | grep -E '(^|/)convert_gt3x_to_csv\.R$' | head -n1 || true)"
          if [[ -z "${script_path}" ]]; then
            echo "❌ Could not find convert_gt3x_to_csv.R anywhere in the repo."
            exit 1
          fi
          echo "Found script at: ${script_path}"
          echo "script=${script_path}" >> "$GITHUB_OUTPUT"

      - name: Run converter
        env:
          DATA_DIR: ${{ github.workspace }}/data   # optional override
        run: |
          set -euo pipefail
          echo "Running: Rscript '${{ steps.find_script.outputs.script }}'"
          Rscript "${{ steps.find_script.outputs.script }}"
          echo "--- data directory listing ---"
          ls -lh data || true

      - name: Upload converted CSVs (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: converted-csvs
          path: |
            data/*.csv
          if-no-files-found: warn
