[influx]
url = "http://localhost:8086"
org = "team1"
bucket = "sheepData"
token = "26cavkn40DHi7euK65j9Gvze349EPJfmejOUEQf7IFbmrPCJ5aEqfg4_O-uQna3urUXIAa7RdD-ir7DYDzC_gA=="

[model]
path = "models/sheep_blstm_model.h5"
labels = ["grazing","lying","mating","running","standing","walking","head-butting","flehmen"]

